[network]
ip = "0.0.0.0"
port = 8000

[tls]
cert = "cert.pem"
key = "privkey.pem"
# enable http, https or both
enabled = "both"

[general]
internal = "/internal"
expires = 120
cleanup = 30
# role for unauthenticated users (defaults to guest)
# guest = "user"

[[statics]]
uri = "/demo"
path = "../ai_wargame_web"

[[users]]
name = "root"
password = "ag3nt"
role = "admin"

[[users]]
name = "student"
password = "s3cr3t"
role = "user"
